In [58]:
import pandas as pd

In [59]:
license_data = pd.read_csv('../active_food_license.csv')
license_data.head()
license_data = license_data.rename(columns={'Address': 'street_address'})
license_data = license_data.rename(columns={'BusinessName': 'name'})
license_data = license_data.rename(columns={'ZIP': 'postal_code'})
license_data['postal_code'] = license_data['postal_code'].str.replace('0','')
# license_data['postal_code'] = license_data['postal_code'].astype(int)
license_data['postal_code'] = license_data['postal_code'].astype(str)
license_data.head(10)

,name,DBAName,street_address,CITY,State,postal_code,LICSTATUS,LICENSECAT,DESCRIPT,LicenseAddDtTm,dayphn,Property_ID,Latitude,Longitude
0,,NaN,73 Chelsea,Charlestown,MA,2129,Active,FS,Eating & Drinking,2012-03-06 12:23:38,10000000000,30258.0,42.372849,-71.058889
1,# 7 RESTAURANT,NaN,225 Grove,West Roxbury,MA,2132,Active,FT,Eating & Drinking w/ Take Out,2007-03-23 15:20:59,10000000000,156965.0,42.261873,-71.157410
2,100 Percent Delicia Food,NaN,635 Hyde Park,Roslindale,MA,2131,Active,FS,Eating & Drinking,2013-02-15 10:46:21,16174774546,77476.0,42.278590,-71.119440
3,100 Percent Delicias Express,NaN,656 Centre,Jamaica Plain,MA,213,Active,FT,Eating & Drinking w/ Take Out,2017-11-28 10:27:47,18572505689,28152.0,42.312830,-71.113860
4,110 Grill,NaN,25 Jan Karski,Dorchester,MA,2125,Active,FS,Eating & Drinking,2018-11-29 14:14:04,19786929450,421286.0,0.000000,0.000000
5,125 Nashua St. Cafe (MGH),NaN,125 Nashua,Boston,MA,2114,Active,FS,Eating & Drinking,2014-08-15 13:03:32,10000000000,340055.0,42.367830,-71.064950
6,129 Lake Street Cafe,NaN,127 LAKE,Brighton/,MA,2135,Active,FS,Eating & Drinking,2010-10-14 12:49:26,16175523307,0.0,0.000000,0.000000
7,149 Eat Street,NaN,300 CHELSEA,Charlestown/,MA,2129,Active,FS,Eating & Drinking,2007-10-11 09:08:52,16177262520,0.0,0.000000,0.000000
8,163 Vietnamese Sandwich,NaN,66 Harrison,BOSTON,MA,2111,Active,FS,Eating & Drinking,2007-08-09 13:26:45,16175427903,NaN,0.000000,0.000000
9,20TH CENTRY BOWLING LANES,NaN,1231 Hyde Park,Hyde Park,MA,2136,Active,FT,Eating & Drinking w/ Take Out,2006-12-07 13:34:04,13392372645,77089.0,42.256820,-71.124110

In [60]:
sg01 = pd.read_csv('sg_01.csv')
sg01 = sg01.rename(columns={'location_name': 'name'})
sg01 = sg01.drop(['safegraph_place_id','safegraph_brand_ids','distance_from_home','related_same_day_brand','related_same_month_brand','device_type'], axis = 1)
# license_data['postal_code'] = license_data['postal_code'].astype(int)
sg01['postal_code'] = sg01['postal_code'].astype(str)
sg01.head(10)

,name,street_address,city,region,postal_code,brands,date_range_start,date_range_end,raw_visit_counts,raw_visitor_counts,visits_by_day,poi_cbg,visitor_home_cbgs,visitor_daytime_cbgs,visitor_work_cbgs,visitor_country_of_origin,median_dwell,bucketed_dwell_times,popularity_by_hour,popularity_by_day
0,Olsen Swimming Pool,95 Turtle Pond Pkwy,Boston,MA,2136,NaN,2020-01-01T00:00:00-05:00,2020-02-01T00:00:00-05:00,476,284,"[2,12,14,30,19,1,25,14,5,11,27,27,8,8,15,11,5,...",2.502598e+11,"{""250214133001"":10,""250251304062"":7,""250214061...","{""250214564022"":10,""250214133001"":10,""25025130...","{""250214133002"":11,""250277501003"":9,""250214412...","{""US"":283}",60.0,"{""<5"":4,""5-20"":96,""21-60"":139,""61-240"":215,"">2...","[16,13,15,12,15,13,17,21,29,40,38,37,40,50,67,...","{""Monday"":70,""Tuesday"":56,""Wednesday"":60,""Thur..."
1,Ilona,783 Tremont St,Boston,MA,2118,NaN,2020-01-01T00:00:00-05:00,2020-02-01T00:00:00-05:00,506,282,"[11,10,22,21,23,14,17,18,27,17,28,23,15,14,21,...",2.502507e+11,"{""250250708002"":10,""250250708001"":9,""250173502...","{""250250709001"":7,""250250806011"":6,""2502501060...","{""250250106001"":5,""360610049001"":4,""2502508050...","{""US"":258}",71.5,"{""<5"":22,""5-20"":135,""21-60"":78,""61-240"":129,"">...","[96,81,85,86,83,80,95,88,93,103,106,101,90,97,...","{""Monday"":57,""Tuesday"":55,""Wednesday"":72,""Thur..."
2,Come Sail Away Now,1 Marina Park Dr Fan Pier,Boston,MA,2210,NaN,2020-01-01T00:00:00-05:00,2020-02-01T00:00:00-05:00,567,204,"[2,20,21,10,3,29,27,24,38,24,14,2,20,26,27,25,...",2.502506e+11,"{""120110106011"":7,""440070117022"":6,""2501735460...","{""250250606001"":31,""330150033012"":5,""360610058...","{""250250606001"":30,""250214223024"":6,""360610137...","{""US"":186}",170.0,"{""<5"":9,""5-20"":88,""21-60"":83,""61-240"":184,"">24...","[6,3,1,0,0,2,34,58,136,213,234,242,254,247,245...","{""Monday"":77,""Tuesday"":90,""Wednesday"":117,""Thu..."
3,Method Advisors,192 South St Ste 600,Boston,MA,2111,NaN,2020-01-01T00:00:00-05:00,2020-02-01T00:00:00-05:00,80,47,"[1,2,5,0,0,3,3,6,3,2,2,1,2,2,3,3,2,2,0,2,1,2,3...",2.502507e+11,"{""250251704003"":4,""090117051023"":4,""2502140020...","{""250250701011"":5,""250214081021"":4,""2502350710...","{""360610101001"":4,""250214135001"":4,""2502507010...","{""US"":43}",120.5,"{""<5"":4,""5-20"":30,""21-60"":3,""61-240"":14,"">240""...","[0,0,0,0,0,0,3,5,28,37,44,56,48,37,30,26,21,10...","{""Monday"":11,""Tuesday"":11,""Wednesday"":14,""Thur..."
4,Longfellow Cafe,150 Riverway,Boston,MA,2215,NaN,2020-01-01T00:00:00-05:00,2020-02-01T00:00:00-05:00,697,198,"[3,1,8,6,2,8,10,9,8,10,18,28,19,24,26,30,32,28...",2.502501e+11,"{""250250103002"":30,""340258095012"":5,""250250102...","{""250250103002"":26,""250250102032"":5,""250251401...","{""250250103002"":21,""250250102043"":5,""250251304...","{""US"":162}",89.0,"{""<5"":12,""5-20"":120,""21-60"":151,""61-240"":211,""...","[157,160,158,159,162,164,156,157,151,150,141,1...","{""Monday"":101,""Tuesday"":100,""Wednesday"":96,""Th..."
5,75 Chestnut,75 Chestnut St,Boston,MA,2108,NaN,2020-01-01T00:00:00-05:00,2020-02-01T00:00:00-05:00,262,128,"[8,10,16,5,6,11,6,10,12,12,4,4,3,9,18,15,13,12...",2.502502e+11,"{""250214061011"":5,""250173423003"":4,""2502503050...","{""250250201012"":6,""250250201011"":5,""2502350910...","{""250092611022"":5,""250250701018"":5,""2502502010...","{""US"":112}",81.0,"{""<5"":6,""5-20"":52,""21-60"":48,""61-240"":88,"">240...","[19,19,20,19,19,19,39,63,84,87,83,86,83,75,60,...","{""Monday"":23,""Tuesday"":26,""Wednesday"":53,""Thur..."
6,Off the Common,50 Park Plz Boston Park Plaza,Boston,MA,2116,NaN,2020-01-01T00:00:00-05:00,2020-02-01T00:00:00-05:00,744,520,"[36,23,14,12,19,18,26,23,26,29,44,37,34,24,33,...",2.502507e+11,"{""250250703001"":12,""271230305003"":7,""201730101...","{""250250703001"":17,""530610517014"":8,""250235221...","{""250214135001"":5,""250250703001"":5,""2502501060...","{""US"":437,""CA"":5,""MX"":4,""BR"":4}",435.5,"{""<5"":19,""5-20"":162,""21-60"":39,""61-240"":74,"">2...","[311,338,347,349,349,341,339,360,353,334,299,2...","{""Monday"":77,""Tuesday"":77,""Wednesday"":138,""Thu..."
7,Central Hill Playground,Central Hill Playground,Boston,MA,2143,NaN,2020-01-01T00:00:00-05:00,2020-02-01T00:00:00-05:00,935,299,"[9,34,38,19,15,39,38,31,38,53,17,17,29,39,46,3...",2.501735e+11,"{""250173513001"":26,""250173502003"":8,""250173513...","{""250173513001"":23,""250173511001"":7,""250173501...","{""250173513001"":40,""250173502004"":6,""250214223...","{""US"":276,""BR"":4}",45.0,"{""<5"":29,""5-20"":270,""21-60"":222,""61-240"":247,""...","[106,104,108,115,123,139,179,181,173,221,194,1...","{""Monday"":122,""Tuesday"":148,""Wednesday"":151,""T..."
8,FedEx,125 Tremont St,Boston,MA,2108,FedEx,2020-01-01T00:00:00-05:00,2020-02-01T00:00:00-05:00,2,2,"[1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...",2.502507e+11,{},{},{},{},4.5,"{""<5"":1,""5-20"":1,""21-60"":0,""61-240"":0,"">240"":0}","[0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]","{""Monday"":0,""Tuesday"":0,""Wednesday"":1,""Thursda..."
9,Dunkin',One Fleet Center4th Floor Lodge,Boston,MA,2114,Dunkin',2020-01-01T00:00:00-05:00,2020-02-01T00:00:00-05:00,747,485,"[8,31,28,22,10,31,29,29,41,28,36,12,25,32,31,3...",2.502502e+11,"{""250173394001"":6,""250214131003"":5,""2502505110...","{""250250203032"":16,""250250408013"":7,""250250901...","{""250250203032"":16,""250250701018"":11,""25025040...","{""US"":447}",20.0,"{""<5"":43,""5-20"":331,""21-60"":112,""61-240"":183,""...","[56,40,24,9,10,32,60,88,118,125,140,142,122,12...","{""Monday"":90,""Tuesday"":103,""Wednesday"":132,""Th..."

In [61]:
common01 = pd.merge(sg01, license_data,on = ['name','postal_code'])
common01 = common01.drop('street_address_y')
common01 = common01.rename(columns={'street_address_x': 'street_address'})
common01

KeyError: "['street_address_y'] not found in axis"

In [62]:
common01.to_csv('01.csv',index=False)
print('Saved file: ' + '01.csv')

Saved file: 01.csv