In [1]:
# imports
import pandas as pd
import numpy as np

In [2]:
# US Census data
table = pd.read_csv('./data/census_tract/census/ACSDP5Y2018.DP03_data_with_overlays_2020-11-12T115259.csv', low_memory=False)

In [3]:
table

,GEO_ID,NAME,DP03_0001E,DP03_0001M,DP03_0001PE,DP03_0001PM,DP03_0002E,DP03_0002M,DP03_0002PE,DP03_0002PM,...,DP03_0135PE,DP03_0135PM,DP03_0136E,DP03_0136M,DP03_0136PE,DP03_0136PM,DP03_0137E,DP03_0137M,DP03_0137PE,DP03_0137PM
0,id,Geographic Area Name,Estimate!!EMPLOYMENT STATUS!!Population 16 yea...,Margin of Error!!EMPLOYMENT STATUS!!Population...,Percent Estimate!!EMPLOYMENT STATUS!!Populatio...,Percent Margin of Error!!EMPLOYMENT STATUS!!Po...,Estimate!!EMPLOYMENT STATUS!!Population 16 yea...,Margin of Error!!EMPLOYMENT STATUS!!Population...,Percent Estimate!!EMPLOYMENT STATUS!!Populatio...,Percent Margin of Error!!EMPLOYMENT STATUS!!Po...,...,Percent Estimate!!PERCENTAGE OF FAMILIES AND P...,Percent Margin of Error!!PERCENTAGE OF FAMILIE...,Estimate!!PERCENTAGE OF FAMILIES AND PEOPLE WH...,Margin of Error!!PERCENTAGE OF FAMILIES AND PE...,Percent Estimate!!PERCENTAGE OF FAMILIES AND P...,Percent Margin of Error!!PERCENTAGE OF FAMILIE...,Estimate!!PERCENTAGE OF FAMILIES AND PEOPLE WH...,Margin of Error!!PERCENTAGE OF FAMILIES AND PE...,Percent Estimate!!PERCENTAGE OF FAMILIES AND P...,Percent Margin of Error!!PERCENTAGE OF FAMILIE...
1,1400000US25001010100,"Census Tract 101, Barnstable County, Massachus...",2829,65,2829,(X),1781,142,63.0,5.0,...,14.9,6.7,(X),(X),3.9,3.3,(X),(X),20.0,6.8
2,1400000US25001010206,"Census Tract 102.06, Barnstable County, Massac...",3129,220,3129,(X),1723,198,55.1,6.1,...,8.5,5.4,(X),(X),1.5,1.6,(X),(X),30.0,16.6
3,1400000US25001010208,"Census Tract 102.08, Barnstable County, Massac...",1122,224,1122,(X),638,194,56.9,10.3,...,6.9,7.7,(X),(X),3.7,5.8,(X),(X),12.2,11.4
4,1400000US25001010304,"Census Tract 103.04, Barnstable County, Massac...",2282,238,2282,(X),1141,214,50.0,7.2,...,3.4,4.4,(X),(X),3.3,2.9,(X),(X),8.8,8.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1474,1400000US25027760100,"Census Tract 7601, Worcester County, Massachus...",2840,102,2840,(X),1878,131,66.1,4.7,...,10.2,6.6,(X),(X),7.1,6.9,(X),(X),8.5,5.6
1475,1400000US25027761100,"Census Tract 7611, Worcester County, Massachus...",4249,198,4249,(X),2793,286,65.7,6.8,...,6.6,7.2,(X),(X),0.0,0.8,(X),(X),23.6,10.8
1476,1400000US25027761200,"Census Tract 7612, Worcester County, Massachus...",4270,295,4270,(X),2648,281,62.0,5.0,...,8.8,7.2,(X),(X),1.6,2.7,(X),(X),16.5,10.0
1477,1400000US25027761300,"Census Tract 7613, Worcester County, Massachus...",2738,177,2738,(X),2022,160,73.8,4.3,...,8.4,8.1,(X),(X),2.5,2.8,(X),(X),25.0,10.3
1478,1400000US25027761400,"Census Tract 7614, Worcester County, Massachus...",5285,143,5285,(X),2900,286,54.9,5.0,...,1.0,2.1,(X),(X),2.3,2.7,(X),(X),18.4,14.1

# Using only the columns of interest
DP03_0021E = Workers 16 and over commuting to work via public transportation
DP03_0022E = Workers 16 and over commuting to work via walking
DP03_0023E = Workers 16 and over commuting to work via other means (not car)
DP03_0026E = Civilian employed population 16 years and over

In [4]:
columns = ['GEO_ID','NAME','DP03_0021E','DP03_0022E','DP03_0023E','DP03_0026E','DP03_0062E']
df = table[columns]

In [5]:
df

,GEO_ID,NAME,DP03_0021E,DP03_0022E,DP03_0023E,DP03_0026E,DP03_0062E
0,id,Geographic Area Name,Estimate!!COMMUTING TO WORK!!Workers 16 years ...,Estimate!!COMMUTING TO WORK!!Workers 16 years ...,Estimate!!COMMUTING TO WORK!!Workers 16 years ...,Estimate!!OCCUPATION!!Civilian employed popula...,Estimate!!INCOME AND BENEFITS (IN 2018 INFLATI...
1,1400000US25001010100,"Census Tract 101, Barnstable County, Massachus...",34,391,208,1658,50741
2,1400000US25001010206,"Census Tract 102.06, Barnstable County, Massac...",26,86,57,1620,69267
3,1400000US25001010208,"Census Tract 102.08, Barnstable County, Massac...",0,1,8,604,65446
4,1400000US25001010304,"Census Tract 103.04, Barnstable County, Massac...",18,0,12,1077,79044
...,...,...,...,...,...,...,...
1474,1400000US25027760100,"Census Tract 7601, Worcester County, Massachus...",2,15,10,1804,68125
1475,1400000US25027761100,"Census Tract 7611, Worcester County, Massachus...",0,24,0,2673,69851
1476,1400000US25027761200,"Census Tract 7612, Worcester County, Massachus...",142,32,38,2511,77938
1477,1400000US25027761300,"Census Tract 7613, Worcester County, Massachus...",33,10,78,1931,94122
1478,1400000US25027761400,"Census Tract 7614, Worcester County, Massachus...",172,51,7,2707,148625

In [7]:
# creating a new column for tract id, which is the last 6 numbers of GEO_ID
df['GEO_ID'] = df['GEO_ID'].apply(lambda x: x[9:])

<ipython-input-7-4014c8c3d7c8>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['GEO_ID'] = df['GEO_ID'].apply(lambda x: x[9:])

In [8]:
df

,GEO_ID,NAME,DP03_0021E,DP03_0022E,DP03_0023E,DP03_0026E,DP03_0062E
0,,Geographic Area Name,Estimate!!COMMUTING TO WORK!!Workers 16 years ...,Estimate!!COMMUTING TO WORK!!Workers 16 years ...,Estimate!!COMMUTING TO WORK!!Workers 16 years ...,Estimate!!OCCUPATION!!Civilian employed popula...,Estimate!!INCOME AND BENEFITS (IN 2018 INFLATI...
1,25001010100,"Census Tract 101, Barnstable County, Massachus...",34,391,208,1658,50741
2,25001010206,"Census Tract 102.06, Barnstable County, Massac...",26,86,57,1620,69267
3,25001010208,"Census Tract 102.08, Barnstable County, Massac...",0,1,8,604,65446
4,25001010304,"Census Tract 103.04, Barnstable County, Massac...",18,0,12,1077,79044
...,...,...,...,...,...,...,...
1474,25027760100,"Census Tract 7601, Worcester County, Massachus...",2,15,10,1804,68125
1475,25027761100,"Census Tract 7611, Worcester County, Massachus...",0,24,0,2673,69851
1476,25027761200,"Census Tract 7612, Worcester County, Massachus...",142,32,38,2511,77938
1477,25027761300,"Census Tract 7613, Worcester County, Massachus...",33,10,78,1931,94122
1478,25027761400,"Census Tract 7614, Worcester County, Massachus...",172,51,7,2707,148625

In [9]:
df.dtypes

GEO_ID        object
NAME          object
DP03_0021E    object
DP03_0022E    object
DP03_0023E    object
DP03_0026E    object
DP03_0062E    object
dtype: object

In [10]:
# removing the first row containing the descriptions for each column
df = df.iloc[1:]
df

,GEO_ID,NAME,DP03_0021E,DP03_0022E,DP03_0023E,DP03_0026E,DP03_0062E
1,25001010100,"Census Tract 101, Barnstable County, Massachus...",34,391,208,1658,50741
2,25001010206,"Census Tract 102.06, Barnstable County, Massac...",26,86,57,1620,69267
3,25001010208,"Census Tract 102.08, Barnstable County, Massac...",0,1,8,604,65446
4,25001010304,"Census Tract 103.04, Barnstable County, Massac...",18,0,12,1077,79044
5,25001010306,"Census Tract 103.06, Barnstable County, Massac...",0,67,41,1087,62553
...,...,...,...,...,...,...,...
1474,25027760100,"Census Tract 7601, Worcester County, Massachus...",2,15,10,1804,68125
1475,25027761100,"Census Tract 7611, Worcester County, Massachus...",0,24,0,2673,69851
1476,25027761200,"Census Tract 7612, Worcester County, Massachus...",142,32,38,2511,77938
1477,25027761300,"Census Tract 7613, Worcester County, Massachus...",33,10,78,1931,94122
1478,25027761400,"Census Tract 7614, Worcester County, Massachus...",172,51,7,2707,148625

In [11]:
# Converting population columns to integers for calculations
pop_columns = ['DP03_0021E','DP03_0022E','DP03_0023E','DP03_0026E']
df[pop_columns] = df[pop_columns].astype(int)
df.dtypes

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pandas/core/frame.py:3069: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

GEO_ID        object
NAME          object
DP03_0021E     int64
DP03_0022E     int64
DP03_0023E     int64
DP03_0026E     int64
DP03_0062E    object
dtype: object

# Calculating impacted population 
Impacted population = the population of workers that use something other than a car to commute to work

In [12]:
df['impacted_pop'] = df.apply(lambda x: x['DP03_0021E'] + x['DP03_0022E'] + x['DP03_0023E'], axis=1)
df

<ipython-input-12-fb6aa7af40c2>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['impacted_pop'] = df.apply(lambda x: x['DP03_0021E'] + x['DP03_0022E'] + x['DP03_0023E'], axis=1)

,GEO_ID,NAME,DP03_0021E,DP03_0022E,DP03_0023E,DP03_0026E,DP03_0062E,impacted_pop
1,25001010100,"Census Tract 101, Barnstable County, Massachus...",34,391,208,1658,50741,633
2,25001010206,"Census Tract 102.06, Barnstable County, Massac...",26,86,57,1620,69267,169
3,25001010208,"Census Tract 102.08, Barnstable County, Massac...",0,1,8,604,65446,9
4,25001010304,"Census Tract 103.04, Barnstable County, Massac...",18,0,12,1077,79044,30
5,25001010306,"Census Tract 103.06, Barnstable County, Massac...",0,67,41,1087,62553,108
...,...,...,...,...,...,...,...,...
1474,25027760100,"Census Tract 7601, Worcester County, Massachus...",2,15,10,1804,68125,27
1475,25027761100,"Census Tract 7611, Worcester County, Massachus...",0,24,0,2673,69851,24
1476,25027761200,"Census Tract 7612, Worcester County, Massachus...",142,32,38,2511,77938,212
1477,25027761300,"Census Tract 7613, Worcester County, Massachus...",33,10,78,1931,94122,121
1478,25027761400,"Census Tract 7614, Worcester County, Massachus...",172,51,7,2707,148625,230

In [33]:
# this column had missing values, represented by a -
df['DP03_0062E'] = df['DP03_0062E'].replace('-', '0')

<ipython-input-33-d6dd6a23467b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['DP03_0062E'] = df['DP03_0062E'].replace('-', '0')

In [31]:
# IGNORE - the issue was solved in the previous cell
df['DP03_0062E'] = df['DP03_0062E'].astype(int)
df.dtypes

ValueError: invalid literal for int() with base 10: '-'

In [32]:
# investigating the previous cell's issue
contain_values = df[df['DP03_0062E'].str.contains('-')]
print(contain_values)

                    GEO_ID                                               NAME  \
57    1400000US25001990000  Census Tract 9900, Barnstable County, Massachu...
222   1400000US25005990000   Census Tract 9900, Bristol County, Massachusetts
227   1400000US25007990000     Census Tract 9900, Dukes County, Massachusetts
390   1400000US25009990100     Census Tract 9901, Essex County, Massachusetts
518   1400000US25015820400  Census Tract 8204, Hampshire County, Massachus...
523   1400000US25015820802  Census Tract 8208.02, Hampshire County, Massac...
865   1400000US25017980000  Census Tract 9800, Middlesex County, Massachus...
871   1400000US25019990000  Census Tract 9900, Nantucket County, Massachus...
1071  1400000US25023525300  Census Tract 5253, Plymouth County, Massachusetts
1102  1400000US25023990003  Census Tract 9900.03, Plymouth County, Massach...
1293  1400000US25025980101  Census Tract 9801.01, Suffolk County, Massachu...
1294  1400000US25025980300   Census Tract 9803, Suffolk County, Massachusetts
1295  1400000US25025980700   Census Tract 9807, Suffolk County, Massachusetts
1296  1400000US25025981000   Census Tract 9810, Suffolk County, Massachusetts
1298  1400000US25025981201  Census Tract 9812.01, Suffolk County, Massachu...
1299  1400000US25025981202  Census Tract 9812.02, Suffolk County, Massachu...
1301  1400000US25025981501  Census Tract 9815.01, Suffolk County, Massachu...
1302  1400000US25025981502  Census Tract 9815.02, Suffolk County, Massachu...
1303  1400000US25025981600   Census Tract 9816, Suffolk County, Massachusetts
1304  1400000US25025981700   Census Tract 9817, Suffolk County, Massachusetts
1305  1400000US25025981800   Census Tract 9818, Suffolk County, Massachusetts
1306  1400000US25025990101  Census Tract 9901.01, Suffolk County, Massachu...
1383  1400000US25027731202  Census Tract 7312.02, Worcester County, Massac...
1407  1400000US25027732902  Census Tract 7329.02, Worcester County, Massac...

      DP03_0021E  DP03_0022E  DP03_0023E  DP03_0026E DP03_0062E tract_id  \
57             0           0           0           0          -   990000
222            0           0           0           0          -   990000
227            0           0           0           0          -   990000
390            0           0           0           0          -   990100
518          153        2445          37        4747     2,500-   820400
523            0         316           9         559          -   820802
865            0           0           0           0          -   980000
871            0           0           0           0          -   990000
1071           0           0           0           0          -   525300
1102           0           0           0           0          -   990003
1293          44           3           0          71          -   980101
1294          10           9           0          62          -   980300
1295           0           0           0           0          -   980700
1296           0           0           0           0          -   981000
1298           0           0           0           0          -   981201
1299           0          69           0          33          -   981202
1301           0           0           0           0          -   981501
1302           0           0           0           0          -   981502
1303           0           0           0           0          -   981600
1304           0           0           0           0          -   981700
1305           0           0           0          12          -   981800
1306          67           0           0          67          -   990101
1383          33         232          17         599          -   731202
1407           6         438          43         951          -   732902

      impacted_pop
57               0
222              0
227              0
390              0
518           2635
523            325
865              0
871              0
1071             0
1102             0
1293            47
1294            19
1295             0
1296             0
1298             0
1299            69
1301             0
1302             0
1303             0
1304             0
1305             0
1306            67
1383           282
1407           487

In [34]:
# done after removing the null values represented by a dash.
contain_values = df[df['DP03_0062E'].str.contains('-')]
print(contain_values)

                   GEO_ID                                               NAME  \
518  1400000US25015820400  Census Tract 8204, Hampshire County, Massachus...

     DP03_0021E  DP03_0022E  DP03_0023E  DP03_0026E DP03_0062E tract_id  \
518         153        2445          37        4747     2,500-   820400

     impacted_pop
518          2635

In [36]:
df.iloc[0,:]

GEO_ID                                       1400000US25001010100
NAME            Census Tract 101, Barnstable County, Massachus...
DP03_0021E                                                     34
DP03_0022E                                                    391
DP03_0023E                                                    208
DP03_0026E                                                   1658
DP03_0062E                                                  50741
tract_id                                                   010100
impacted_pop                                                  633
Name: 1, dtype: object

In [37]:
# a dataset we worked with previously showed that the tract with tract_id = 820400 had an income of 2499
# that dataset can be found here: https://api.census.gov/data/2018/acs/acs5?get=B19013_001E&for=tract:*&in=state:25
# this was used in Deliverable 1's calculations
df['DP03_0062E'] = df['DP03_0062E'].replace('2,500-', '2499')

<ipython-input-37-3d2f8083a08b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['DP03_0062E'] = df['DP03_0062E'].replace('2,500-', '2499')

In [38]:
contain_values = df[df['DP03_0062E'].str.contains('-')]
print(contain_values)

Empty DataFrame
Columns: [GEO_ID, NAME, DP03_0021E, DP03_0022E, DP03_0023E, DP03_0026E, DP03_0062E, tract_id, impacted_pop]
Index: []

In [13]:
# renaming columns
df = df.rename(columns={'DP03_0021E': 'public_transport', 'DP03_0022E': 'walking', 'DP03_0023E':'other', 'DP03_0026E':'total_employed', 'DP03_0062E':'income'})

In [14]:
df

,GEO_ID,NAME,public_transport,walking,other,total_employed,income,impacted_pop
1,25001010100,"Census Tract 101, Barnstable County, Massachus...",34,391,208,1658,50741,633
2,25001010206,"Census Tract 102.06, Barnstable County, Massac...",26,86,57,1620,69267,169
3,25001010208,"Census Tract 102.08, Barnstable County, Massac...",0,1,8,604,65446,9
4,25001010304,"Census Tract 103.04, Barnstable County, Massac...",18,0,12,1077,79044,30
5,25001010306,"Census Tract 103.06, Barnstable County, Massac...",0,67,41,1087,62553,108
...,...,...,...,...,...,...,...,...
1474,25027760100,"Census Tract 7601, Worcester County, Massachus...",2,15,10,1804,68125,27
1475,25027761100,"Census Tract 7611, Worcester County, Massachus...",0,24,0,2673,69851,24
1476,25027761200,"Census Tract 7612, Worcester County, Massachus...",142,32,38,2511,77938,212
1477,25027761300,"Census Tract 7613, Worcester County, Massachus...",33,10,78,1931,94122,121
1478,25027761400,"Census Tract 7614, Worcester County, Massachus...",172,51,7,2707,148625,230

In [15]:
cols = ['GEO_ID','public_transport','walking','other','total_employed','impacted_pop']
final_df = df[cols]
final_df

,GEO_ID,public_transport,walking,other,total_employed,impacted_pop
1,25001010100,34,391,208,1658,633
2,25001010206,26,86,57,1620,169
3,25001010208,0,1,8,604,9
4,25001010304,18,0,12,1077,30
5,25001010306,0,67,41,1087,108
...,...,...,...,...,...,...
1474,25027760100,2,15,10,1804,27
1475,25027761100,0,24,0,2673,24
1476,25027761200,142,32,38,2511,212
1477,25027761300,33,10,78,1931,121
1478,25027761400,172,51,7,2707,230

In [16]:
final_df.to_csv("./output/tracts_with_population.csv")

In [2]:
import pandas as pd
pd.read_csv("./output/tracts_with_population.csv").dtypes

Unnamed: 0          int64
GEO_ID              int64
public_transport    int64
walking             int64
other               int64
total_employed      int64
impacted_pop        int64
dtype: object