In [1]:
import pandas as pd
import numpy as np

X = pd.read_csv('new_data.csv', parse_dates = True, low_memory = False)
print(X.shape)

(1796941, 14)

In [2]:
X.head()

,[2020-10-08 15:26:29] production_jobs.INFO: Customer Id,User Id,User Created At,Activation Date,Activity Date,Name,Content Type,Journey Name,Action,Duration,Device,Channel,Session Id,Rating
0,[2020-10-08 15:26:29] production_jobs.INFO: 8,147,2018-09-26 12:19:32,2018-09-25 21:05:24,2018-09-27 09:30:53,Welcome to Journey,INTERNAL_VIDEO,Welcome,0,NaN,Web,Direct Connection,eDE0NzY2Mg==,-
1,[2020-10-08 15:26:29] production_jobs.INFO: 9,139,2018-09-21 17:14:07,2018-09-22 10:00:02,2018-10-01 11:18:20,İnovasyoncunun Beş Alışkanlığı,INFOGRAPHIC,İnovatif Bakış Açısı,100,NaN,Web,Direct Connection,eDEzOTY1MQ==,-
2,[2020-10-08 15:26:29] production_jobs.INFO: 9,139,2018-09-21 17:14:07,2018-09-23 10:00:59,2018-10-01 11:19:18,Peter Drucker’a göre İnovasyona Fırsat Sağlaya...,INTERNAL_ARTICLE,İnovatif Bakış Açısı,100,NaN,Web,Direct Connection,eDEzOTY1Mg==,-
3,[2020-10-08 15:26:29] production_jobs.INFO: 10,200,2018-10-03 09:36:25,2018-10-01 08:00:36,2018-10-03 09:48:55,Welcome to Journey,INTERNAL_VIDEO,İnovatif Bakış Açısı,0,NaN,Web,Direct Connection,eDIwMDY4Ng==,-
4,[2020-10-08 15:26:29] production_jobs.INFO: 10,200,2018-10-03 09:36:25,2018-10-01 09:00:52,2018-10-03 10:38:28,Yenilikçinin İkilemi,INTERNAL_VIDEO,İnovatif Bakış Açısı,0,NaN,Web,Direct Connection,eDIwMDY4Nw==,-

In [3]:
X = X.values

In [4]:
res_list = X.T.tolist()
b = list(set(res_list[10]))

device = X[:,11]
for i in range(len(device)):
    if device[i] == 'Device':
        print(i)
        
content_type = X[:,6]
for i in range(len(content_type)):
    if content_type[i] == 'Content Type':
        print(i)
#print(b)

34
69
104

In [5]:

device = X[:,11]
#print(device)
channel = X[:,12]
#print(channel)
content_type = X[:,6]
#print(content_type)
for i in range(len(device)):
    if device[i] == 'Android':
        device[i] = 4
    elif device[i] == 'iOS':
        device[i] = 3    
    elif device[i] == 'Web':
        device[i] = 2 
    elif device[i] == 'Mobile Web (Tablet)':
        device[i] = 1
    elif device[i] == 'Mobile Web':
        device[i] = 5
    else:
        device[i] = 0
print(device)

for i in range(len(channel)):
    if channel[i] == 'Mobile Notification':
        channel[i] = 2
    elif channel[i] == 'From Email':
        channel[i] = 1
    elif channel[i] == 'Direct Connection':
        channel[i] = 3
    else:
        channel[i] = 0
#print(channel)

content_type_list = ['KEY_CONTACT_NEWHIRE', 'EXTERNAL_ARTICLE', 'CHECKLIST', 'KNOWLEDGE_REQUIREMENT_NEWHIRE', 'BOOK_SUGGESTION', 'QUIZ', 'KEY_CONTACT_MANAGER', 'EXTERNAL_VIDEO', 'SURVEY', 'MEETING', 'LIVE_EVENT', 'INTERNAL_ARTICLE', 'FLIPBOOK', 'KNOWLEDGE_REQUIREMENT_MANAGER', 'INFOGRAPHIC', 'Content Type', 'INTERNAL_VIDEO', 'QUOTES']

for i in range(len(content_type)):
    if content_type[i] == content_type_list[0]:
        content_type[i] = 17
    elif content_type[i] == content_type_list[1]:
        content_type[i] = 1
    elif content_type[i] == content_type_list[2]:
        content_type[i] = 2
    elif content_type[i] == content_type_list[3]:
        content_type[i] = 3
    elif content_type[i] == content_type_list[4]:
        content_type[i] = 4
    elif content_type[i] == content_type_list[5]:
        content_type[i] = 5
    elif content_type[i] == content_type_list[6]:
        content_type[i] = 6
    elif content_type[i] == content_type_list[7]:
        content_type[i] = 7
    elif content_type[i] == content_type_list[8]:
        content_type[i] = 8
    elif content_type[i] == content_type_list[9]:
        content_type[i] = 9
    elif content_type[i] == content_type_list[10]:
        content_type[i] = 10
    elif content_type[i] == content_type_list[11]:
        content_type[i] = 11
    elif content_type[i] == content_type_list[12]:
        content_type[i] = 12
    elif content_type[i] == content_type_list[13]:
        content_type[i] = 13
    elif content_type[i] == content_type_list[14]:
        content_type[i] = 14
    elif content_type[i] == content_type_list[15]:
        content_type[i] = 15
    elif content_type[i] == content_type_list[16]:
        content_type[i] = 16
    else:
        content_type[i] = 0
#print(content_type)

[0 0 0 ... 0 0 0]

In [6]:
clean_data = pd.DataFrame(X)
print(clean_data.head())
c = clean_data.values
#print(c)

                                               0    1                    2   \
0   [2020-10-08 15:26:29] production_jobs.INFO: 8  147  2018-09-26 12:19:32
1   [2020-10-08 15:26:29] production_jobs.INFO: 9  139  2018-09-21 17:14:07
2   [2020-10-08 15:26:29] production_jobs.INFO: 9  139  2018-09-21 17:14:07
3  [2020-10-08 15:26:29] production_jobs.INFO: 10  200  2018-10-03 09:36:25
4  [2020-10-08 15:26:29] production_jobs.INFO: 10  200  2018-10-03 09:36:25

                    3                    4   \
0  2018-09-25 21:05:24  2018-09-27 09:30:53
1  2018-09-22 10:00:02  2018-10-01 11:18:20
2  2018-09-23 10:00:59  2018-10-01 11:19:18
3  2018-10-01 08:00:36  2018-10-03 09:48:55
4  2018-10-01 09:00:52  2018-10-03 10:38:28

                                                  5   6   \
0                                 Welcome to Journey  16
1                     İnovasyoncunun Beş Alışkanlığı  14
2  Peter Drucker’a göre İnovasyona Fırsat Sağlaya...  11
3                                 Welcome to Journey  16
4                               Yenilikçinin İkilemi  16

                      7    8    9    10 11 12   13
0               Welcome     0  NaN  Web  0  0  -
1  İnovatif Bakış Açısı   100  NaN  Web  0  0  -
2  İnovatif Bakış Açısı   100  NaN  Web  0  0  -
3  İnovatif Bakış Açısı     0  NaN  Web  0  0  -
4  İnovatif Bakış Açısı     0  NaN  Web  0  0  -

In [7]:
max_value = clean_data[11].mode()
clean_data[11] = clean_data[11].replace([0],max_value)
print(clean_data[11].value_counts())

0    1796941
Name: 11, dtype: int64

In [8]:
content_max = clean_data[6].mode()
#print(content_max)
print(clean_data[6].value_counts())


clean_data[6] = clean_data[6].replace([0],content_max)
#print('after: ',clean_data[6].value_counts())

16    525608
7     433870
12    282862
11    148846
14    144520
1     103192
4      36226
2      33977
5      33819
0      26730
8      23563
10      3019
9        653
3         37
17         8
6          7
15         3
13         1
Name: 6, dtype: int64

In [9]:
max_value = clean_data[12].mode()
clean_data[12] = clean_data[12].replace([0],max_value)
print(clean_data[12].value_counts())

0    1796941
Name: 12, dtype: int64

In [10]:
clean_data.drop(clean_data[clean_data[1] == 'FLIPBOOK'].index, inplace = True)

In [11]:
clean_data.dropna(how = 'any', axis = 0, inplace = True)

In [12]:
clean_data.reset_index(inplace=True, drop=True)

In [13]:
clean_data[1] = clean_data[1].fillna(0.0).astype('int')

ValueError: invalid literal for int() with base 10: 'User Id'

In [14]:
clean_data[9] = clean_data[9].replace(['nan'],'0')
clean_data[9] = clean_data[9].fillna(0.0).astype('int')

ValueError: invalid literal for int() with base 10: '00:00:00'

In [15]:
#clean_data.drop(index = 1789049, axis = 0)
clean_data[5] = clean_data[5].replace(['nan'],"")
clean_data[5] = clean_data[5].astype('str')

In [16]:
clean_data.columns = ['Customer Id','User Id', 'User Created At', 'Activation Date', 'Activity Date','Name', 'Content Type', 'Content ID','Journey Name', 'Action', 'Duration','Device', 'Channel', 'Session Id', 'Rating']

ValueError: Length mismatch: Expected axis has 14 elements, new values have 15 elements

In [17]:
#clean_data = clean_data[:300].groupby(['User Id'],axis=1)
#print(Grouped.size())

clean_data.groupby(['User Id'])

#print(clean_data.groupby(['User Id']).count())

group_label = clean_data.groupby(['User Id']).groups
print(group_label)

KeyError: 'User Id'

In [18]:
open_time = pd.DataFrame()
open_time = clean_data.loc[:, ('User Id','Activation Date','Activity Date','Name','Action','User Created At')]
#diff = pd.Timestamp(open_time['Activity Date'])- pd.Timestamp(open_time['Activation Date'])
#diff = pd.to_datetime(open_time['Activity Date'])- pd.to_datetime(open_time['Activation Date'])
#print(diff)
#open_time.insert(5, "Time lag", diff)
print(open_time)
#open_time.dropna(how = "any")

KeyError: "None of [Index(['User Id', 'Activation Date', 'Activity Date', 'Name', 'Action',\n       'User Created At'],\n      dtype='object')] are in the [columns]"

In [127]:
date = open_time['Activity Date'].map(lambda x: str(x)[0:10])

In [128]:
date = pd.to_datetime(date)

In [129]:
open_time['Activity Day'] = date.dt.day_name()

In [130]:
hr = open_time['Activity Date'].map(lambda x: str(x)[11:13])

In [131]:
open_time['hour'] = hr

# Action == 100

In [200]:
Action100 = open_time[open_time.loc[:,("Action")] == 100]

In [201]:
type(open_time['Activity Day'][0])

str

In [202]:
def tonum(x):
    """
    take x, activity day as input
    return int Mon -> 100, Tue -> , etc
    """
    if x == "Monday":
        #print("1")
        return 100
    elif x == "Tuesday":
        return 200
    elif x == "Wednesday":
        return 300
    elif x == "Thursday":
        return 400
    elif x == "Friday":
        return 500
    elif x == "Saturday":
        return 600
    else:
        return 700

In [203]:
day_num = open_time.loc[:,('Activity Day')].map(lambda x: tonum(x))

In [204]:
#day_num = day_num.to_frame()

In [205]:
Action100["day_num"] = day_num

/Users/rqshi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [206]:
hr_num = Action100['hour'].map(lambda x: int(x))

In [207]:
Action100["hour"] = hr_num

/Users/rqshi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [209]:
total_num = Action100['hour'].add(Action100['day_num'])

In [212]:
Action100['total_num'] = total_num

/Users/rqshi/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [213]:
Action100.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 820423 entries, 0 to 1904924
Data columns (total 10 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   User Id          820423 non-null  int64
 1   Activation Date  820423 non-null  object
 2   Activity Date    820423 non-null  object
 3   Name             820423 non-null  object
 4   Action           820423 non-null  int64
 5   User Created At  820423 non-null  object
 6   Activity Day     820423 non-null  object
 7   hour             820423 non-null  int64
 8   day_num          820423 non-null  int64
 9   total_num        820423 non-null  int64
dtypes: int64(5), object(5)
memory usage: 68.9+ MB

In [214]:
Action100.head()

,User Id,Activation Date,Activity Date,Name,Action,User Created At,Activity Day,hour,day_num,total_num
0,217,2018-10-11 16:15:13,2018-10-13 23:06:41,LMS tarihe karışıyor: LXP dünyasına hoş geldiniz!,100,2018-10-09 13:37:22,Saturday,23,600,623
1,217,2018-10-11 11:52:48,2018-10-13 23:06:46,Silikon Vadisinden en son İK ve Eğitim Trendleri,100,2018-10-09 13:37:22,Saturday,23,600,623
2,217,2018-10-06 10:00:06,2018-10-13 23:06:58,Drucker’a göre İnovasyon Fırsatı Sağlayan Yedi...,100,2018-10-09 13:37:22,Saturday,23,600,623
3,217,2018-10-05 08:00:34,2018-10-15 14:30:20,8 maddede yıkıcı inovasyon,100,2018-10-09 13:37:22,Monday,14,100,114
4,217,2018-10-05 08:00:34,2018-10-15 14:30:49,8 maddede yıkıcı inovasyon,100,2018-10-09 13:37:22,Monday,14,100,114

In [238]:
df100 = pd.DataFrame({'User Id':Action100["User Id"].unique()})

In [239]:
df100['total_num'] = [list(set(Action100['total_num'].loc[Action100['User Id'] == x['User Id']])) for _, x in df100.iterrows()]

In [241]:
df100.head()

   User Id                                          total_num
0      217  [512, 312, 611, 408, 423, 617, 618, 623, 208, ...
1      242  [512, 320, 708, 109, 208, 114, 309, 214, 215, ...
2       69                               [312, 313, 512, 111]
3      308                                    [602, 419, 415]
4      304                          [416, 321, 610, 422, 221]

In [249]:
df = Action100.groupby('User Id').agg(lambda x: x.tolist())

In [251]:
df.head()

,Activation Date,Activity Date,Name,Action,User Created At,Activity Day,hour,day_num,total_num
User Id,,,,,,,,,
21,"[2018-10-31 13:32:19, 2018-11-01 08:30:57, 201...","[2018-10-31 14:08:53, 2018-11-01 08:33:27, 201...",[Çalışan Bağlılığı 3.0: Kişiye Özel “Nudge (Dü...,"[100, 100, 100, 100, 100, 100, 100, 100, 100, ...","[2018-05-14 02:49:06, 2018-05-14 02:49:06, 201...","[Wednesday, Thursday, Thursday, Thursday, Wedn...","[14, 8, 8, 8, 11, 9, 15, 15, 15, 15, 16, 16, 8]","[300, 400, 400, 400, 300, 400, 300, 300, 300, ...","[314, 408, 408, 408, 311, 409, 315, 315, 315, ..."
38,"[2019-10-03 08:00:00, 2019-10-03 09:00:00]","[2019-10-04 03:12:57, 2019-10-04 03:13:10]","[demo flip, safety]","[100, 100]","[2018-05-14 17:59:52, 2018-05-14 17:59:52]","[Friday, Friday]","[3, 3]","[500, 500]","[503, 503]"
41,"[2019-02-21 16:00:00, 2019-02-21 16:39:00, 201...","[2019-02-22 08:16:24, 2019-02-22 08:17:25, 201...","[Makas, Hakan Ateş'ten Denizcilerimize Mesajla...","[100, 100, 100, 100, 100, 100, 100, 100, 100, ...","[2018-05-16 19:43:48, 2018-05-16 19:43:48, 201...","[Friday, Friday, Friday, Friday, Friday, Monda...","[8, 8, 11, 14, 15, 14, 15, 15, 15, 9, 10, 23, ...","[500, 500, 500, 500, 500, 100, 400, 100, 100, ...","[508, 508, 511, 514, 515, 114, 415, 115, 115, ..."
47,"[2020-10-07 12:45:00, 2020-10-07 12:45:00, 202...","[2020-10-07 14:27:21, 2020-10-07 14:27:22, 202...","[Ekipleri Uzaktan Etkili Yönetmek, Ekipleri Uz...","[100, 100, 100]","[2018-06-21 08:01:03, 2018-06-21 08:01:03, 201...","[Wednesday, Wednesday, Wednesday]","[14, 14, 14]","[300, 300, 300]","[314, 314, 314]"
53,"[2018-11-01 08:30:57, 2018-11-08 08:30:00, 201...","[2018-11-17 13:04:53, 2018-11-17 13:06:15, 201...",[Çalışan Bağlılığı 3.0: Kişiye Özel “Nudge (Dü...,"[100, 100, 100]","[2018-06-27 07:53:16, 2018-06-27 07:53:16, 201...","[Saturday, Saturday, Saturday]","[13, 13, 13]","[600, 600, 600]","[613, 613, 613]"

In [258]:
index_df = df.index.values

In [268]:
df["count_total"] = ''

In [264]:
from collections import Counter
def count(x):
    Counter(df["total_num"][21]).most_common()

[(315, 4), (408, 3), (116, 2), (314, 1), (311, 1), (409, 1), (208, 1)]

In [270]:
for i in range(len(index_df)):
    df['count_total'][index_df[i]] = Counter(df['total_num'][index_df[i]]).most_common()

In [271]:
df.head()

,Activation Date,Activity Date,Name,Action,User Created At,Activity Day,hour,day_num,total_num,count_total
User Id,,,,,,,,,,
21,"[2018-10-31 13:32:19, 2018-11-01 08:30:57, 201...","[2018-10-31 14:08:53, 2018-11-01 08:33:27, 201...",[Çalışan Bağlılığı 3.0: Kişiye Özel “Nudge (Dü...,"[100, 100, 100, 100, 100, 100, 100, 100, 100, ...","[2018-05-14 02:49:06, 2018-05-14 02:49:06, 201...","[Wednesday, Thursday, Thursday, Thursday, Wedn...","[14, 8, 8, 8, 11, 9, 15, 15, 15, 15, 16, 16, 8]","[300, 400, 400, 400, 300, 400, 300, 300, 300, ...","[314, 408, 408, 408, 311, 409, 315, 315, 315, ...","[(315, 4), (408, 3), (116, 2), (314, 1), (311,..."
38,"[2019-10-03 08:00:00, 2019-10-03 09:00:00]","[2019-10-04 03:12:57, 2019-10-04 03:13:10]","[demo flip, safety]","[100, 100]","[2018-05-14 17:59:52, 2018-05-14 17:59:52]","[Friday, Friday]","[3, 3]","[500, 500]","[503, 503]","[(503, 2)]"
41,"[2019-02-21 16:00:00, 2019-02-21 16:39:00, 201...","[2019-02-22 08:16:24, 2019-02-22 08:17:25, 201...","[Makas, Hakan Ateş'ten Denizcilerimize Mesajla...","[100, 100, 100, 100, 100, 100, 100, 100, 100, ...","[2018-05-16 19:43:48, 2018-05-16 19:43:48, 201...","[Friday, Friday, Friday, Friday, Friday, Monda...","[8, 8, 11, 14, 15, 14, 15, 15, 15, 9, 10, 23, ...","[500, 500, 500, 500, 500, 100, 400, 100, 100, ...","[508, 508, 511, 514, 515, 114, 415, 115, 115, ...","[(410, 63), (309, 17), (111, 14), (416, 14), (..."
47,"[2020-10-07 12:45:00, 2020-10-07 12:45:00, 202...","[2020-10-07 14:27:21, 2020-10-07 14:27:22, 202...","[Ekipleri Uzaktan Etkili Yönetmek, Ekipleri Uz...","[100, 100, 100]","[2018-06-21 08:01:03, 2018-06-21 08:01:03, 201...","[Wednesday, Wednesday, Wednesday]","[14, 14, 14]","[300, 300, 300]","[314, 314, 314]","[(314, 3)]"
53,"[2018-11-01 08:30:57, 2018-11-08 08:30:00, 201...","[2018-11-17 13:04:53, 2018-11-17 13:06:15, 201...",[Çalışan Bağlılığı 3.0: Kişiye Özel “Nudge (Dü...,"[100, 100, 100]","[2018-06-27 07:53:16, 2018-06-27 07:53:16, 201...","[Saturday, Saturday, Saturday]","[13, 13, 13]","[600, 600, 600]","[613, 613, 613]","[(613, 3)]"

In [365]:
def sort_arr(arr):
    res = [[],[],[],[],[],[],[]]
    for i in range(len(arr)):
        item = str(arr[i][0])
        if item[0] == "1":
            res[0].append(arr[i])
            #return res
        elif item[0] == "2":
            res[1].append(arr[i])
            #return res
        elif item[0] == "3":
            res[2].append(arr[i])
            #return res
        elif item[0] == "4":
            res[3].append(arr[i])
            #return res
        elif item[0] == "5":
            res[4].append(arr[i])
            #return res
        elif item[0] == "6":
            res[5].append(arr[i])
            #return res
        else:
            res[6].append(arr[i])
            #return res
    return res
def get_max(arr):
    l = []
    for i in range(len(arr)):
        l.append(arr[i][-1])
    return max(l)
def find_freq(arr):
    res = []
    sorted_arr = sort_arr(arr)
    for i in range(len(sorted_arr)):
        if len(sorted_arr[i]) == 0:
            res.append([])
        else:
            if len(sorted_arr[i]) == 1:
                res.append(sorted_arr[i])
            else:
                subarr = sorted_arr[i]
                l = []
                m = get_max(subarr)
                for j in range(len(subarr)):
                    if subarr[j][-1] == m:
                        l.append(subarr[j])
                res.append(l)
    return res

In [366]:
df["every_day_freq"] = ''

In [369]:
for i in range(len(index_df)):
    arr = df["count_total"][index_df[i]]
    df["every_day_freq"][index_df[i]] = find_freq(arr)

In [370]:
df.head()

,Activation Date,Activity Date,Name,Action,User Created At,Activity Day,hour,day_num,total_num,count_total,every_day_freq
User Id,,,,,,,,,,,
21,"[2018-10-31 13:32:19, 2018-11-01 08:30:57, 201...","[2018-10-31 14:08:53, 2018-11-01 08:33:27, 201...",[Çalışan Bağlılığı 3.0: Kişiye Özel “Nudge (Dü...,"[100, 100, 100, 100, 100, 100, 100, 100, 100, ...","[2018-05-14 02:49:06, 2018-05-14 02:49:06, 201...","[Wednesday, Thursday, Thursday, Thursday, Wedn...","[14, 8, 8, 8, 11, 9, 15, 15, 15, 15, 16, 16, 8]","[300, 400, 400, 400, 300, 400, 300, 300, 300, ...","[314, 408, 408, 408, 311, 409, 315, 315, 315, ...","[(315, 4), (408, 3), (116, 2), (314, 1), (311,...","[[(116, 2)], [(208, 1)], [(315, 4)], [(408, 3)..."
38,"[2019-10-03 08:00:00, 2019-10-03 09:00:00]","[2019-10-04 03:12:57, 2019-10-04 03:13:10]","[demo flip, safety]","[100, 100]","[2018-05-14 17:59:52, 2018-05-14 17:59:52]","[Friday, Friday]","[3, 3]","[500, 500]","[503, 503]","[(503, 2)]","[[], [], [], [], [(503, 2)], [], []]"
41,"[2019-02-21 16:00:00, 2019-02-21 16:39:00, 201...","[2019-02-22 08:16:24, 2019-02-22 08:17:25, 201...","[Makas, Hakan Ateş'ten Denizcilerimize Mesajla...","[100, 100, 100, 100, 100, 100, 100, 100, 100, ...","[2018-05-16 19:43:48, 2018-05-16 19:43:48, 201...","[Friday, Friday, Friday, Friday, Friday, Monda...","[8, 8, 11, 14, 15, 14, 15, 15, 15, 9, 10, 23, ...","[500, 500, 500, 500, 500, 100, 400, 100, 100, ...","[508, 508, 511, 514, 515, 114, 415, 115, 115, ...","[(410, 63), (309, 17), (111, 14), (416, 14), (...","[[(111, 14)], [(210, 9), (215, 9)], [(309, 17)..."
47,"[2020-10-07 12:45:00, 2020-10-07 12:45:00, 202...","[2020-10-07 14:27:21, 2020-10-07 14:27:22, 202...","[Ekipleri Uzaktan Etkili Yönetmek, Ekipleri Uz...","[100, 100, 100]","[2018-06-21 08:01:03, 2018-06-21 08:01:03, 201...","[Wednesday, Wednesday, Wednesday]","[14, 14, 14]","[300, 300, 300]","[314, 314, 314]","[(314, 3)]","[[], [], [(314, 3)], [], [], [], []]"
53,"[2018-11-01 08:30:57, 2018-11-08 08:30:00, 201...","[2018-11-17 13:04:53, 2018-11-17 13:06:15, 201...",[Çalışan Bağlılığı 3.0: Kişiye Özel “Nudge (Dü...,"[100, 100, 100]","[2018-06-27 07:53:16, 2018-06-27 07:53:16, 201...","[Saturday, Saturday, Saturday]","[13, 13, 13]","[600, 600, 600]","[613, 613, 613]","[(613, 3)]","[[], [], [], [], [], [(613, 3)], []]"

In [381]:
df['Mon'] = ''
df['Tue'] = ''
df['Wed'] = ''
df['Thu'] = ''
df['Fri'] = ''
df['Sat'] = ''
df['Sun'] = ''

In [389]:
for i in range(len(index_df)):
    arr = df["every_day_freq"][index_df[i]]
    temp = []
    ### Monday
    if len(arr[0]) == 0:
        df['Mon'][index_df[i]] = [np.nan]
    else:
        if len(arr[0]) == 1:
            df['Mon'][index_df[i]] = [arr[0][0][0]%100]
        else:
            for j in range(len(arr[0])):
                temp.append(arr[0][j][0]%100)
                df['Mon'][index_df[i]] = temp
    ### Tuesday
    if len(arr[1]) == 0:
        df['Tue'][index_df[i]] = [np.nan]
    else:
        if len(arr[1]) == 1:
            df['Tue'][index_df[i]] = [arr[1][0][0]%100]
        else:
            for j in range(len(arr[1])):
                temp.append(arr[1][j][0]%100)
                df['Tue'][index_df[i]] = temp
    ### Wednesday
    if len(arr[2]) == 0:
        df['Wed'][index_df[i]] = [np.nan]
    else:
        if len(arr[2]) == 1:
            df['Wed'][index_df[i]] = [arr[2][0][0]%100]
        else:
            for j in range(len(arr[2])):
                temp.append(arr[2][j][0]%100)
                df['Wed'][index_df[i]] = temp
    ### Thursday
    if len(arr[3]) == 0:
        df['Thu'][index_df[i]] = [np.nan]
    else:
        if len(arr[3]) == 1:
            df['Thu'][index_df[i]] = [arr[3][0][0]%100]
        else:
            for j in range(len(arr[3])):
                temp.append(arr[3][j][0]%100)
                df['Thu'][index_df[i]] = temp
    ### Friday
    if len(arr[4]) == 0:
        df['Fri'][index_df[i]] = [np.nan]
    else:
        if len(arr[4]) == 1:
            df['Fri'][index_df[i]] = [arr[4][0][0]%100]
        else:
            for j in range(len(arr[4])):
                temp.append(arr[4][j][0]%100)
                df['Fri'][index_df[i]] = temp
    ### Saturday
    if len(arr[5]) == 0:
        df['Sat'][index_df[i]] = [np.nan]
    else:
        if len(arr[5]) == 1:
            df['Sat'][index_df[i]] = [arr[5][0][0]%100]
        else:
            for j in range(len(arr[5])):
                temp.append(arr[5][j][0]%100)
                df['Sat'][index_df[i]] = temp
    ### Sunday
    if len(arr[6]) == 0:
        df['Sun'][index_df[i]] = [np.nan]
    else:
        if len(arr[6]) == 1:
            df['Sun'][index_df[i]] = [arr[6][0][0]%100]
        else:
            for j in range(len(arr[6])):
                temp.append(arr[6][j][0]%100)
                df['Sun'][index_df[i]] = temp

In [390]:
df.head()

,Activation Date,Activity Date,Name,Action,User Created At,Activity Day,hour,day_num,total_num,count_total,every_day_freq,Mon,Tue,Wed,Thu,Fri,Sat,Sun
User Id,,,,,,,,,,,,,,,,,,
21,"[2018-10-31 13:32:19, 2018-11-01 08:30:57, 201...","[2018-10-31 14:08:53, 2018-11-01 08:33:27, 201...",[Çalışan Bağlılığı 3.0: Kişiye Özel “Nudge (Dü...,"[100, 100, 100, 100, 100, 100, 100, 100, 100, ...","[2018-05-14 02:49:06, 2018-05-14 02:49:06, 201...","[Wednesday, Thursday, Thursday, Thursday, Wedn...","[14, 8, 8, 8, 11, 9, 15, 15, 15, 15, 16, 16, 8]","[300, 400, 400, 400, 300, 400, 300, 300, 300, ...","[314, 408, 408, 408, 311, 409, 315, 315, 315, ...","[(315, 4), (408, 3), (116, 2), (314, 1), (311,...","[[(116, 2)], [(208, 1)], [(315, 4)], [(408, 3)...",[16],[8],[15],[8],[nan],[nan],[nan]
38,"[2019-10-03 08:00:00, 2019-10-03 09:00:00]","[2019-10-04 03:12:57, 2019-10-04 03:13:10]","[demo flip, safety]","[100, 100]","[2018-05-14 17:59:52, 2018-05-14 17:59:52]","[Friday, Friday]","[3, 3]","[500, 500]","[503, 503]","[(503, 2)]","[[], [], [], [], [(503, 2)], [], []]",[nan],[nan],[nan],[nan],[3],[nan],[nan]
41,"[2019-02-21 16:00:00, 2019-02-21 16:39:00, 201...","[2019-02-22 08:16:24, 2019-02-22 08:17:25, 201...","[Makas, Hakan Ateş'ten Denizcilerimize Mesajla...","[100, 100, 100, 100, 100, 100, 100, 100, 100, ...","[2018-05-16 19:43:48, 2018-05-16 19:43:48, 201...","[Friday, Friday, Friday, Friday, Friday, Monda...","[8, 8, 11, 14, 15, 14, 15, 15, 15, 9, 10, 23, ...","[500, 500, 500, 500, 500, 100, 400, 100, 100, ...","[508, 508, 511, 514, 515, 114, 415, 115, 115, ...","[(410, 63), (309, 17), (111, 14), (416, 14), (...","[[(111, 14)], [(210, 9), (215, 9)], [(309, 17)...",[11],"[10, 15]",[9],[10],[9],[17],[12]
47,"[2020-10-07 12:45:00, 2020-10-07 12:45:00, 202...","[2020-10-07 14:27:21, 2020-10-07 14:27:22, 202...","[Ekipleri Uzaktan Etkili Yönetmek, Ekipleri Uz...","[100, 100, 100]","[2018-06-21 08:01:03, 2018-06-21 08:01:03, 201...","[Wednesday, Wednesday, Wednesday]","[14, 14, 14]","[300, 300, 300]","[314, 314, 314]","[(314, 3)]","[[], [], [(314, 3)], [], [], [], []]",[nan],[nan],[14],[nan],[nan],[nan],[nan]
53,"[2018-11-01 08:30:57, 2018-11-08 08:30:00, 201...","[2018-11-17 13:04:53, 2018-11-17 13:06:15, 201...",[Çalışan Bağlılığı 3.0: Kişiye Özel “Nudge (Dü...,"[100, 100, 100]","[2018-06-27 07:53:16, 2018-06-27 07:53:16, 201...","[Saturday, Saturday, Saturday]","[13, 13, 13]","[600, 600, 600]","[613, 613, 613]","[(613, 3)]","[[], [], [], [], [], [(613, 3)], []]",[nan],[nan],[nan],[nan],[nan],[13],[nan]

In [391]:
customer100 = pd.DataFrame()
customer100 = df.loc[:,('Mon','Tue','Wed','Thu','Fri','Sat','Sun')]

In [392]:
customer100.head()

           Mon       Tue    Wed    Thu    Fri    Sat    Sun
User Id
21        [16]       [8]   [15]    [8]  [nan]  [nan]  [nan]
38       [nan]     [nan]  [nan]  [nan]    [3]  [nan]  [nan]
41        [11]  [10, 15]    [9]   [10]    [9]   [17]   [12]
47       [nan]     [nan]   [14]  [nan]  [nan]  [nan]  [nan]
53       [nan]     [nan]  [nan]  [nan]  [nan]   [13]  [nan]